config/routes.rb
Rails.application.routes.draw do
  resources :payees

  resources :transactions

 root 'home#index'
 
 resources :home
 resources :accounts
 resources :cards
 resources :loans
 resources :internetbanking
 
end

app/models/payee.rb
class Payee < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

end

app/controllers/internetbanking_controller.rb
class InternetbankingController < ApplicationController
  def index

  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index

  end
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  before_action :set_payee, only: [:show, :edit, :update, :destroy]

  # GET /payees
  # GET /payees.json
  def index
    @payees = Payee.all
  end

  # GET /payees/1
  # GET /payees/1.json
  def show
  end

  # GET /payees/new
  def new
    @payee = Payee.new
  end

  # GET /payees/1/edit
  def edit
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)

    respond_to do |format|
      if @payee.save
        format.html { redirect_to @payee, notice: 'Payee was successfully created.' }
        format.json { render :show, status: :created, location: @payee }
      else
        format.html { render :new }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to @payee, notice: 'Payee was successfully updated.' }
        format.json { render :show, status: :ok, location: @payee }
      else
        format.html { render :edit }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    respond_to do |format|
      format.html { redirect_to payees_url, notice: 'Payee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payee
      @payee = Payee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payee_params
      params.require(:payee).permit(:nick_name, :account_name, :bsb, :account_number)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from_account, :to_account, :amount, :balance, :payment_date, :remarks)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/internetbanking_helper.rb
module InternetbankingHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h2> INDEX </h2>
		<p>
			This is my Accounts Index page
		</p>
	</div>
</div>

app/views/cards/index.html.erb
<div class="container">
   <div class="jumbotron">
	<h2> INDEX </h2>
		<p>
			This is my Cards Index page
		</p>
   </div>
</div>

app/views/home/index.html.erb
<div class="container">
   <div class="jumbotron">
      	<h2> RoR Bank </h2>
			<p>
				RoR Bank is an Banking application developed using Ruby on Rails
			</p>
			<br>
			<h4> Accounts </h4>
			<p>
				This option lists all the Accounts that are avilable with RoR Bank, Account Fee, Maintenance, etc
			</p>

			<h4> Cards </h4>
			<p>
				This option lists all the Cards that are avilable with RoR Bank, Account Fee, Maintenance, etc
			</p>
			<h4> Loans </h4>
			<p>
				This option lists all the Loans that are avilable with RoR Bank, Account Fee, Maintenance, etc
			</p>

			<h4> Internet Banking </h4>
			<p>
				This option lists provides you rich online services for your Banking
			</p>

   </div>
</div>

app/views/internetbanking/index.html.erb
<div class="container">
   <div class="jumbotron">
      <h2>Welcome to RoR Virtual Internet banking </h2>
      <p>To use Internet Banking services, please sign in</p>
      <p><a class="btn btn-primary" role="button">
         Sign In</a>
      </p>
   </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<nav class="navbar navbar-default header navbar-fixed-bottom footer" role="navigation">
		<div class="container-fluid">

			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-left">
					<li>
						<a href="#">About Us</a>
					</li>
					<li>
						<a href="#">Contact Us</a>
					</li>
					<li>
						<a href="#">Copy Rights</a>
					</li>
				</ul>

			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default header" role="navigation">
  <div class="container-fluid">
 
    <div class="navbar-header">
     <a class="navbar-brand" href="home#index">RoR Bank</a>
    </div>
    <div class="collapse navbar-collapse">
    	<ul class="nav navbar-nav navbar-left">
        <li><a href="accounts#index">Accounts</a></li>
        <li><a href="cards#index">Cards</a></li>
        <li><a href="loans#index">Loans</a></li>
        <li><a href="internetbanking#index">Internet Banking</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Keyword, press Enter">
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Signup</a></li>
        <li><a href="#">Signin</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Imagenation</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<%= yield %>
		<%= render 'layouts/footer' %>

	</body>
</html>

app/views/loans/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h2> INDEX </h2>
		<p>
			This is my Loans Index page
		</p>
	</div>
</div>

app/views/payees/_form.html.erb
<%= form_for(@payee) do |f| %>
<% if @payee.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@payee.errors.count, "error") %> prohibited this payee from being saved:</h2>

	<ul>
		<% @payee.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table class="table table-striped">

	<tbody>
		<tr>
			<td><%= f.label :nick_name %></td>
			<td><%= f.text_field :nick_name %></td>
		</tr>
		<tr>
			<td> <%= f.label :account_name %></td>
			<td><%= f.text_field :account_name %></td>
		</tr>
		<tr>
			<td> <%= f.label :bsb %></td>
			<td> <%= f.number_field :bsb %></td>
		</tr>
		<tr>
			<td><%= f.label :account_number %></td>
			<td> <%= f.number_field :account_number %></td>
		</tr>
	</tbody>
</table>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/payees/edit.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>Editing payee</h2>

<%= render 'form' %>

<%= link_to 'Show', @payee, class: "btn btn-primary"  %> |
<%= link_to 'Back', payees_path, class: "btn btn-primary" %>
</div></div>

app/views/payees/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>Listing payees</h2>

		<table class="table table-striped">
			<thead>
				<tr>
					<th>Nick name</th>
					<th>Account name</th>
					<th>Bsb</th>
					<th>Account number</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @payees.each do |payee| %>
				<tr>
					<td><%= payee.nick_name %></td>
					<td><%= payee.account_name %></td>
					<td><%= payee.bsb %></td>
					<td><%= payee.account_number %></td>
					<td><%= link_to 'Show', payee, class: "btn btn-primary btn-xs" %></td>
					<td><%= link_to 'Edit', edit_payee_path(payee), class: "btn btn-warning btn-xs"  %></td>
					<td><%= link_to 'Destroy', payee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"  %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<br>

		<%= link_to 'New Payee', new_payee_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/payees/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>New payee</h2>

		<%= render 'form' %>

		<%= link_to 'Back', payees_path, class: "btn btn-primary"  %>
	</div>
</div>

app/views/payees/show.html.erb
<div class="container">
	<div class="jumbotron">
		<p id="notice">
			<%= notice %>
		</p>

		<p>
			<strong>Nick name:</strong>
			<%= @payee.nick_name %>
		</p>

		<p>
			<strong>Account name:</strong>
			<%= @payee.account_name %>
		</p>

		<p>
			<strong>Bsb:</strong>
			<%= @payee.bsb %>
		</p>

		<p>
			<strong>Account number:</strong>
			<%= @payee.account_number %>
		</p>

		<%= link_to 'Edit', edit_payee_path(@payee), class: "btn btn-primary" %> |
		<%= link_to 'Back', payees_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
<% if @transaction.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

	<ul>
		<% @transaction.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table class="table table-striped">
	<tbody>
		<tr>
			<td><%= f.label :from_account %></td>
			<td><%= f.text_field :from_account %></td>
		</tr>
		<tr>
			<td><%= f.label :to_account %></td>
			<td><%= f.text_field :to_account %></td>
		</tr>
		<tr>
			<td><%= f.label :amount %></td>
			<td><%= f.text_field :amount %></td>
		</tr>
		<tr>
			<td><%= f.label :balance %></td>
			<td><%= f.text_field :balance %></td>
		</tr>
		<tr>
			<td><%= f.label :payment_date %></td>
			<td><%= f.date_select :payment_date %></td>
		</tr>
		<tr>
			<td><%= f.label :remarks %></td>
			<td><%= f.text_field :remarks %></td>
		</tr>
	</tbody>
</table>

<div class="actions">
	<%= f.submit%>
</div>
<% end %>

app/views/transactions/edit.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>Editing transaction</h2>

		<%= render 'form' %>

		<%= link_to 'Show', @transaction, class: "btn btn-primary" %> |
		<%= link_to 'Back', transactions_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/transactions/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>Listing transactions</h2>

		<table class="table table-striped">
			<thead>
				<tr>
					<th>From account</th>
					<th>To account</th>
					<th>Amount</th>
					<th>Balance</th>
					<th>Payment date</th>
					<th>Remarks</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @transactions.each do |transaction| %>
				<tr>
					<td><%= transaction.from_account %></td>
					<td><%= transaction.to_account %></td>
					<td><%= transaction.amount %></td>
					<td><%= transaction.balance %></td>
					<td><%= transaction.payment_date %></td>
					<td><%= transaction.remarks %></td>
					<td><%= link_to 'Show', transaction, class: "btn btn-primary btn-xs"  %></td>
					<td><%= link_to 'Edit', edit_transaction_path(transaction), class: "btn btn-warning btn-xs"  %></td>
					<td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"  %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<br>

		<%= link_to 'New Transaction', new_transaction_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/transactions/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h2>New transaction</h2>

		<%= render 'form' %>

		<%= link_to 'Back', transactions_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/transactions/show.html.erb
<div class="container">
	<div class="jumbotron">
		<p id="notice">
			<%= notice %>
		</p>

		<p>
			<strong>From account:</strong>
			<%= @transaction.from_account %>
		</p>

		<p>
			<strong>To account:</strong>
			<%= @transaction.to_account %>
		</p>

		<p>
			<strong>Amount:</strong>
			<%= @transaction.amount %>
		</p>

		<p>
			<strong>Balance:</strong>
			<%= @transaction.balance %>
		</p>

		<p>
			<strong>Payment date:</strong>
			<%= @transaction.payment_date %>
		</p>

		<p>
			<strong>Remarks:</strong>
			<%= @transaction.remarks %>
		</p>

		<%= link_to 'Edit', edit_transaction_path(@transaction), class: "btn btn-primary" %> |
		<%= link_to 'Back', transactions_path, class: "btn btn-primary" %>
	</div>
</div>